<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <PackageId>DynamicDataCore</PackageId>
    <Version>2.1.2</Version>
    <Authors>César Adolfo Solís Alvarez</Authors>
    <Company>CelestialDevelopment</Company>
    <Copyright>Copyright (c) 2025-2026 César Adolfo Solís Alvarez (CelestialDevelopment)</Copyright>
    <Description>Lightweight and extensible data access framework for .NET applications. Supports multi-database, keyset/cursor pagination, and async streaming via EF Core.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/CesarSoftNica175/DynamicDataCore</RepositoryUrl>
    <PackageProjectUrl>https://github.com/CesarSoftNica175/DynamicDataCore</PackageProjectUrl>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>DynamicDataCore.Infrastructure</AssemblyName>
    <RootNamespace>DynamicDataCore.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EfCoreVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EfCoreVersion)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="$(MsExtensionsVersion)" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="$(MsExtensionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(MsExtensionsVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DynamicDataCore.Abstractions\DynamicDataCore.Abstractions.csproj" />
  </ItemGroup>

</Project>
